//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PottiEntities2 : DbContext
    {
        public PottiEntities2()
            : base("name=PottiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Reservation> Reservations { get; set; }
    
        public virtual ObjectResult<Sp_GetAll_Result> Sp_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetAll_Result>("Sp_GetAll");
        }
    }
}
