//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp1
    {
        public string Name { get; set; }
        public int id { get; set; }
        public Nullable<decimal> phonenumber { get; set; }
        public string Address { get; set; }
        public string city { get; set; }
        public string Country { get; set; }
        public Nullable<int> age { get; set; }

        
    }
}
